server:
  port: 5000

logging:
  config: 'classpath:logback.xml'

zuul:
  routes:
    core-service:
      path: /api/**
      url: http://58.182.223.185:7070/
    ui:
      path: /**
      url: http://localhost:3000/
